services:
  users-app:
    build: .
    environment:
      - 'USERS_APP={"username": "postgres", "password": "123456", "host": "localhost", "port": "5432", "dbname": "users_app_db"}'
    ports:
      - "8080:8080"

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=postgres
      - POSTGRES_DB=users_app_db
    ports:
      - "5432:5432"